import Head from "next/head";
import CustomNavbar from "/components/CustomNavbar";

export default function Home() {
    return (
    <div>
        <Head>
            <title>Pedrenrique Analytics</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <CustomNavbar />
        <h1>Contato</h1>
    </div>
    )
}
